name: Tests (against typescript@latest in Node.js v22)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ubuntu/Node v22
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Install latest peer dependencies
        run: pnpm add typescript@latest @types/node@22
        working-directory: packages/knip
      - name: Build knip
        run: pnpm run build
        working-directory: packages/knip
      - name: Test knip
        run: pnpm run test:node
        working-directory: packages/knip
      - name: Run knip
        run: ./packages/knip/bin/knip.js
      - name: Run knip in strict mode
        run: ./packages/knip/bin/knip.js --production --strict
